target("epico")
	set_kind("binary")
	add_files("main.cpp")
	set_languages("cxx20")
	add_packages("fmt", "libsdl", "glm", "stb", "spdlog", "assimp", "ktx")
	add_deps("imgui")
	add_defines("GLM_FORCE_DEPTH_ZERO_TO_ONE", "GLM_ENABLE_EXPERIMENTAL")
	add_includedirs("$(projectdir)/source/", "$(projectdir)/thirdparty/imgui/")
	add_rules("defaults_rule", { precompiled_header = path.absolute("./stdafx.h") })
	set_default(true)