target("epico")
	set_kind("binary")
	add_files("main.cpp")
	set_languages("cxx20")
	add_packages("fmt", "libsdl", "glm", "stb", "spdlog", "assimp")
	add_includedirs("$(projectdir)/source/")
	add_rules("defaults_rule", { precompiled_header = path.absolute("./stdafx.h") })
	set_default(true)