target("shaders")
	set_kind("object")
	add_rules("utils.glsl2spv", { outputdir = "$(projectdir)/output/assets/shaders" })
	add_files("shaders/*.vert", "shaders/*.frag", "shaders/*.geom")
	add_packages("glslang")
	add_rules("defaults_rule")
	on_install(function(target)
		--print(path.join(target:installdir(), "assets/shaders"))
		--os.cp(, path.join(target:installdir(), "assets/shaders"))
	end)