option("filesystem_std_spew")
	set_default(true)
	set_showmenu(true)
	add_defines("CONFIG_SPEW")
	set_category("filesystem_std")
	set_description("Extended Logging")

target("filesystem_std")
	set_kind("shared")
	set_languages("cxx20")
	add_files("*.cpp")
	add_defines("EAPI_EXPORT")
	add_includedirs("$(projectdir)/source")
	add_packages("fmt", "spdlog")
	add_rules("defaults_rule", { precompiled_header = path.absolute("./stdafx.h") })
	add_options("filesystem_std_spew")