#include "vkconvert.h"

CONVERTER(convert_image_format, ImageFormat, VkFormat, VK_FORMAT_UNDEFINED,
	{ R8G8B8A8_UNORM, VK_FORMAT_R8G8B8A8_UNORM },
	{ R8G8B8A8_SNORM, VK_FORMAT_R8G8B8A8_SNORM },
	{ R16G16B16A16_UINT, VK_FORMAT_R16G16B16A16_UINT },
	{ R16G16B16A16_SINT, VK_FORMAT_R16G16B16A16_SINT },
	{ R16G16B16A16_SFLOAT, VK_FORMAT_R16G16B16A16_SFLOAT }
);

CONVERTER(convert_sample_bits, ImageSamples, VkSampleCountFlagBits, VK_SAMPLE_COUNT_1_BIT,
	{ SAMPLE_COUNT_1_BIT, VK_SAMPLE_COUNT_1_BIT },
	{ SAMPLE_COUNT_2_BIT, VK_SAMPLE_COUNT_2_BIT },
	{ SAMPLE_COUNT_4_BIT, VK_SAMPLE_COUNT_4_BIT },
	{ SAMPLE_COUNT_8_BIT, VK_SAMPLE_COUNT_8_BIT },
	{ SAMPLE_COUNT_16_BIT, VK_SAMPLE_COUNT_16_BIT },
	{ SAMPLE_COUNT_32_BIT, VK_SAMPLE_COUNT_32_BIT },
	{ SAMPLE_COUNT_64_BIT, VK_SAMPLE_COUNT_64_BIT }
);

CONVERTER(convert_buffer_type, BufferType, VkBufferUsageFlagBits, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
	{ VERTEX, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT },
	{ INDEX, VK_BUFFER_USAGE_INDEX_BUFFER_BIT },
	{ STORAGE, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT }
);

CONVERTER(convert_image_dimensions, ImageDimensions, VkImageType, VK_IMAGE_TYPE_1D,
	{ IMAGE_1D, VK_IMAGE_TYPE_1D },
	{ IMAGE_2D, VK_IMAGE_TYPE_2D },
	{ IMAGE_3D, VK_IMAGE_TYPE_3D },
);

CONVERTER(convert_image_view_dimensions, ImageDimensions, VkImageViewType, VK_IMAGE_VIEW_TYPE_1D,
	{ IMAGE_1D, VK_IMAGE_VIEW_TYPE_1D },
	{ IMAGE_2D, VK_IMAGE_VIEW_TYPE_2D },
	{ IMAGE_3D, VK_IMAGE_VIEW_TYPE_3D },
);

CONVERTER(convert_attribute_format, AttributeType, VkFormat, VK_FORMAT_UNDEFINED,
	{ VEC4D_SIGNED, VK_FORMAT_R32G32B32A32_SFLOAT },
	{ VEC3D_SIGNED, VK_FORMAT_R32G32B32_SFLOAT },
	{ VEC2D_SIGNED, VK_FORMAT_R32G32_SFLOAT },
	{ VEC1D_SIGNED, VK_FORMAT_R32_SFLOAT },
);

CONVERTER(convert_shader_stage, ShaderStage, VkShaderStageFlagBits, VK_SHADER_STAGE_VERTEX_BIT,
	{ STAGE_VERTEX, VK_SHADER_STAGE_VERTEX_BIT },
	{ STAGE_FRAGMENT, VK_SHADER_STAGE_FRAGMENT_BIT },
);

CONVERTER(convert_binding_rate, BindingRate, VkVertexInputRate, VK_VERTEX_INPUT_RATE_VERTEX,
	{ RATE_VERTEX, VK_VERTEX_INPUT_RATE_VERTEX },
	{ RATE_INDEX, VK_VERTEX_INPUT_RATE_INSTANCE },
);
