#include "vkconvert.h"

CONVERTER(convert_image_format, ImageFormat, VkFormat, VK_FORMAT_UNDEFINED,
    { R16G16B16A16_UINT, VK_FORMAT_R16G16B16A16_UINT },
    { R16G16B16A16_SINT, VK_FORMAT_R16G16B16A16_SINT },
    { R16G16B16A16_SFLOAT, VK_FORMAT_R16G16B16A16_SFLOAT }
);

CONVERTER(convert_sample_bits, ImageSample, VkSampleCountFlagBits, VK_SAMPLE_COUNT_1_BIT,
    { SAMPLE_COUNT_1_BIT, VK_SAMPLE_COUNT_1_BIT },
    { SAMPLE_COUNT_2_BIT, VK_SAMPLE_COUNT_2_BIT },
    { SAMPLE_COUNT_4_BIT, VK_SAMPLE_COUNT_4_BIT },
    { SAMPLE_COUNT_8_BIT, VK_SAMPLE_COUNT_8_BIT },
    { SAMPLE_COUNT_16_BIT, VK_SAMPLE_COUNT_16_BIT },
    { SAMPLE_COUNT_32_BIT, VK_SAMPLE_COUNT_32_BIT },
    { SAMPLE_COUNT_64_BIT, VK_SAMPLE_COUNT_64_BIT }
);

